apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}-prod
  namespace: ${{ values.argoNS }}
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: ${{ values.argoProject }}
  source:
    path: ${{ values.argoComponentOverlays }}/prod
    repoURL: ${{ values.repoURL }}.git
    targetRevision: main
  destination:
    namespace: ${{ values.namespace }}-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: ${{ values.argoNS }}
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
