apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ${{ values.name }} 
  name: ${{ values.name }}
spec:
  ports:
  - port: ${{ values.port }} 
    targetPort: ${{ values.port }} 
  selector:
    app.kubernetes.io/instance: ${{ values.name }} 
